### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by grigy** [tmartiro/pebble_arm_cyr_langpack#1]
Thanks for making this. I'm original Pebble user and any time I get a message in Armenian I think that this font issue needs to be solved. Glad someone did it finally.

Could you provide instructions on how to install the langpack on a Pebble device? A link to other resources would also work.

**Comment by tmartiro** [comment]
բարև Գրիգ  ջան,

Navigate to release section of the repository where you can download language pack **arm_cyr.pbl**.  
Then follow the manual:
Manuals: [How to install language pack on Android](https://github.com/MarSoft/pebble-firmware-utils/wiki/How-to-install-language-pack-on-Android), or [How to install language pack on iOS](https://github.com/MarSoft/pebble-firmware-utils/wiki/How-to-install-language-pack-on-iOS).

**Comment by grigy** [comment]
Thanks Տիկ ջան. It worked!
